#!/usr/bin/env bash
clear
cat << !
Welcome to checkn1x-surface.

Alt+F1 : Welcome
Alt+F2 : Checkra1n
Alt+F3 : Checkra1n CLI-mode
Alt+F4 : Usbmuxd (debug)
Alt+F5 : Shell (debug)

Connected USB devices:
`lsusb | cut -c24-`
!

# Shoutout SO
# https://askubuntu.com/a/1126732
# https://stackoverflow.com/a/67920337
ReadKey() {
	if read -sN1 KEY; then
		while read -sN1 -t 0.001; do
			KEY+="${REPLY}"
		done
	fi
}

declare -a fnkey
for x in {1..24}; do
    raw=$(tput kf$x | cat -A)
    fnkey[$x]=${raw#^[}
done

while ReadKey; do
	case "${KEY}" in
		$'\e'${fnkey[1]})
			/usr/local/bin/checkn1x_welcome
			;;
		$'\e'${fnkey[2]})
			/usr/local/bin/checkra1n
			;;
		$'\e'${fnkey[3]})
			read -sp "Press enter to run checkra1n in CLI mode."
			exec /usr/local/bin/checkra1n -cqv
			;;
		$'\e'${fnkey[4]})
			/usr/sbin/usbmuxd -f
			;;
		$'\e'${fnkey[5]})
			/bin/login -f root
			;;
	esac
done
