name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y ca-certificates \
                            cpio \
                            curl \
                            debootstrap \
                            grub2-common \
                            grub-efi-amd64-bin \
                            grub-pc-bin \
                            gzip \
                            mtools \
                            tar \
                            xorriso \
                            xz-utils

    - name: Build
      run: |
        sudo ./build.sh && sudo mv -v work/*.iso .

    - name: Publish release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"
        gh release upload "$TAG" ./*.iso
